export default function Page() {
  const links = [
    ["/device-continuity", "Device Continuity Command Center"],
    ["/device-continuity-index", "Device Continuity Index"],
    ["/device-continuity-risk-matrix", "Device Continuity Risk Matrix"],
    ["/android-samsung-continuity", "Android / Samsung Continuity"],
    ["/wireless-debugging-locked-stub", "Wireless Debugging Locked Stub"],
    ["/smartthings-locked-stub", "SmartThings Locked Stub"],
    ["/apple-continuity-locked-stub", "Apple Continuity Locked Stub"],
    ["/display-casting-locked-stub", "Display Casting Locked Stub"]
  ];

  const proof = [
    ["388 Expansion Contract", "CLEAN"],
    ["389 Risk Matrix Contract", "CLEAN"],
    ["390 UI/API Stub Contract", "CLEAN"],
    ["391 Locked Stub Creation", "CLEAN"],
    ["392 Locked Stub Index", "CLEAN"]
  ];

  return (
    <main style={{ minHeight: "100vh", padding: "48px", background: "#05070d", color: "#f8fafc", fontFamily: "Arial, sans-serif" }}>
      <section style={{ maxWidth: "1120px", margin: "0 auto" }}>
        <p style={{ color: "#38bdf8", fontSize: "14px", letterSpacing: "0.14em", textTransform: "uppercase", marginBottom: "12px" }}>
          LeeWay Device Continuity Master Status
        </p>

        <h1 style={{ fontSize: "44px", lineHeight: "1.08", margin: "0 0 16px" }}>
          Device Continuity Master Status
        </h1>

        <p style={{ fontSize: "18px", lineHeight: "1.7", color: "#cbd5e1", maxWidth: "920px" }}>
          This is the locked master navigation surface for the Device Continuity expansion lane. It proves the continuity pages and API routes exist, but remain locked, non-executing, and blocked from device control.
        </p>

        <div style={{ marginTop: "24px", padding: "20px", border: "1px solid #7f1d1d", borderRadius: "18px", background: "rgba(127,29,29,0.28)" }}>
          <strong style={{ color: "#fecaca" }}>LOCKED / NO EXECUTE:</strong>
          <span style={{ color: "#fee2e2" }}> No ADB, DeX, Smart View, SmartThings, Apple, Bluetooth, Quick Share, screen recording, camera, microphone, router, phone, TV, lock, appliance, or physical action is authorized here.</span>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(230px,1fr))", gap: "14px", marginTop: "28px" }}>
          {[
            ["Locked", "true"],
            ["Approval Granted", "false"],
            ["Authority Unlocked", "false"],
            ["Execution Authorized", "false"],
            ["Device Control Authorized", "false"],
            ["Physical Action Authorized", "false"]
          ].map(([label, value]) => (
            <div key={label} style={{ border: "1px solid #1e293b", background: "#0f172a", borderRadius: "16px", padding: "18px" }}>
              <div style={{ color: "#94a3b8", fontSize: "13px" }}>{label}</div>
              <div style={{ color: "#f8fafc", fontSize: "18px", fontWeight: 700, marginTop: "6px" }}>{value}</div>
            </div>
          ))}
        </div>

        <h2 style={{ marginTop: "36px", fontSize: "26px" }}>Proof chain</h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(240px,1fr))", gap: "12px" }}>
          {proof.map(([label, value]) => (
            <div key={label} style={{ border: "1px solid #164e63", background: "rgba(8,47,73,0.45)", borderRadius: "14px", padding: "16px" }}>
              <div style={{ color: "#bae6fd", fontWeight: 700 }}>{label}</div>
              <div style={{ color: "#67e8f9", marginTop: "6px" }}>{value}</div>
            </div>
          ))}
        </div>

        <h2 style={{ marginTop: "36px", fontSize: "26px" }}>Locked Device Continuity navigation</h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(260px,1fr))", gap: "12px" }}>
          {links.map(([href, label]) => (
            <a key={href} href={href} style={{ display: "block", textDecoration: "none", color: "#f8fafc", border: "1px solid #1e293b", background: "#0f172a", borderRadius: "16px", padding: "18px" }}>
              <div style={{ fontWeight: 700 }}>{label}</div>
              <div style={{ color: "#94a3b8", marginTop: "8px", fontSize: "13px" }}>{href}</div>
              <div style={{ color: "#fca5a5", marginTop: "10px", fontSize: "13px" }}>Locked / GET only / no execute</div>
            </a>
          ))}
        </div>

        <p style={{ color: "#64748b", marginTop: "32px", fontSize: "13px" }}>
          Generated by 393-device-continuity-master-status-and-nav-link.ps1
        </p>
      </section>
    </main>
  );
}
