"""
Execution Bridge

Bridges parsed intents to SEA execution with 9E learning integration.
"""

from typing import Dict, Any, Optional
from dataclasses import dataclass
from datetime import datetime
import asyncio

from .intent_parser import Intent
from .voice_identity_engine import VoiceIdentityEngine, VoiceOutput


@dataclass
class ExecutionRequest:
    """Request for SEA execution"""
    request_id: str
    intent: Intent
    sea_action: str
    sea_params: Dict[str, Any]
    priority: str
    created_at: str


@dataclass
class ExecutionResponse:
    """Response from SEA execution"""
    request_id: str
    success: bool
    result: Any
    voice_response: VoiceOutput
    execution_time_ms: float
    receipt_path: Optional[str]


class ExecutionBridge:
    """Bridges intents to SEA execution"""
    
    def __init__(self):
        self.voice_engine = VoiceIdentityEngine()
        self.pending_requests: Dict[str, ExecutionRequest] = {}
    
    async def execute_intent(
        self,
        intent: Intent,
        sea_executor: Optional[Any] = None
    ) -> ExecutionResponse:
        """
        Execute parsed intent through SEA.
        
        Args:
            intent: Parsed intent
            sea_executor: Optional SEA executor (for testing)
            
        Returns:
            ExecutionResponse with result and voice response
        """
        start_time = datetime.utcnow()
        
        # Create execution request
        request = self._create_execution_request(intent)
        self.pending_requests[request.request_id] = request
        
        try:
            # Execute through SEA
            if sea_executor:
                result = await self._execute_through_sea(request, sea_executor)
            else:
                result = await self._simulate_execution(request)
            
            # Generate voice response
            voice_response = self._generate_voice_response(intent, result)
            
            # Calculate execution time
            execution_time = (datetime.utcnow() - start_time).total_seconds() * 1000
            
            # Create response
            response = ExecutionResponse(
                request_id=request.request_id,
                success=result.get("success", False),
                result=result,
                voice_response=voice_response,
                execution_time_ms=execution_time,
                receipt_path=result.get("receipt_path")
            )
            
            # Generate voice receipt (audio_path would be set after TTS generation)
            # Skipping receipt generation here as audio_path is not yet available
            # Will be generated by TTS layer
            
            return response
            
        finally:
            # Clean up pending request
            self.pending_requests.pop(request.request_id, None)
    
    def _create_execution_request(self, intent: Intent) -> ExecutionRequest:
        """Create SEA execution request from intent"""
        request_id = f"req-{datetime.utcnow().strftime('%Y%m%d%H%M%S%f')}"
        
        # Map intent to SEA action
        sea_action, sea_params = self._map_intent_to_sea(intent)
        
        # Determine priority
        priority = self._determine_priority(intent)
        
        return ExecutionRequest(
            request_id=request_id,
            intent=intent,
            sea_action=sea_action,
            sea_params=sea_params,
            priority=priority,
            created_at=datetime.utcnow().isoformat()
        )
    
    def _map_intent_to_sea(self, intent: Intent) -> tuple[str, Dict[str, Any]]:
        """Map intent to SEA action and parameters"""
        action_map = {
            # Commands
            "create": ("create_file", {"path": intent.entities.get("target")}),
            "modify": ("modify_file", {"path": intent.entities.get("target")}),
            "delete": ("delete_file", {"path": intent.entities.get("target")}),
            "read": ("read_file", {"path": intent.entities.get("target")}),
            "list": ("list_files", {"path": intent.entities.get("target", ".")}),
            "search": ("search_files", {"query": intent.entities.get("target")}),
            "execute": ("execute_command", {"command": intent.entities.get("target")}),
            "start": ("start_service", {"service": intent.entities.get("target")}),
            "stop": ("stop_service", {"service": intent.entities.get("target")}),
            "check": ("check_status", {"target": intent.entities.get("target")}),
            "verify": ("verify_state", {"target": intent.entities.get("target")}),
            "test": ("run_test", {"target": intent.entities.get("target")}),
            
            # Questions
            "what_is": ("query_knowledge", {"query": intent.entities.get("target")}),
            "what_are": ("query_knowledge", {"query": intent.entities.get("target")}),
            "where_is": ("locate_resource", {"resource": intent.entities.get("target")}),
            "where_are": ("locate_resource", {"resource": intent.entities.get("target")}),
            "how_to": ("get_instructions", {"task": intent.entities.get("target")}),
            "why": ("explain_reason", {"subject": intent.entities.get("target")}),
            "when": ("get_timing", {"event": intent.entities.get("target")}),
            "who": ("get_attribution", {"subject": intent.entities.get("target")}),
            "capability_check": ("check_capability", {"capability": intent.entities.get("target")}),
            
            # Special
            "greet": ("greet_user", {}),
            "conversation": ("converse", {"message": intent.raw_input}),
        }
        
        return action_map.get(intent.action, ("unknown_action", {}))
    
    def _determine_priority(self, intent: Intent) -> str:
        """Determine execution priority"""
        # High priority for system commands
        high_priority_actions = ["stop", "delete", "verify", "check"]
        if intent.action in high_priority_actions:
            return "high"
        
        # Low priority for queries
        query_actions = ["what_is", "what_are", "where_is", "how_to"]
        if intent.action in query_actions:
            return "low"
        
        return "normal"
    
    async def _execute_through_sea(
        self,
        request: ExecutionRequest,
        sea_executor: Any
    ) -> Dict[str, Any]:
        """Execute request through SEA"""
        # This would integrate with actual SEA
        # For now, delegate to executor
        return await sea_executor.execute(
            action=request.sea_action,
            params=request.sea_params,
            priority=request.priority
        )
    
    async def _simulate_execution(self, request: ExecutionRequest) -> Dict[str, Any]:
        """Simulate execution for testing"""
        await asyncio.sleep(0.1)  # Simulate work
        
        return {
            "success": True,
            "action": request.sea_action,
            "params": request.sea_params,
            "result": f"Simulated execution of {request.sea_action}",
            "receipt_path": None
        }
    
    def _generate_voice_response(
        self,
        intent: Intent,
        result: Dict[str, Any]
    ) -> VoiceOutput:
        """Generate voice response based on result"""
        # Determine response context
        if result.get("success"):
            context = self._get_success_context(intent)
            text = self._generate_success_text(intent, result)
        else:
            context = "error"
            text = self._generate_error_text(intent, result)
        
        # Apply voice identity
        return self.voice_engine.apply_voice_identity(text, context)
    
    def _get_success_context(self, intent: Intent) -> str:
        """Get voice context for successful execution"""
        if intent.intent_type == "greeting":
            return "greeting"
        elif intent.action in ["check", "verify"]:
            return "status"
        else:
            return "completion"
    
    def _generate_success_text(
        self,
        intent: Intent,
        result: Dict[str, Any]
    ) -> str:
        """Generate success response text"""
        action = intent.action
        
        # Greeting responses
        if action == "greet":
            return "Hello. I'm Agent Lee. Ready to assist."
        
        # Command responses
        if action in ["create", "modify", "delete"]:
            return f"Task complete. {action.capitalize()} operation successful."
        
        if action == "read":
            return "File read successfully. Content retrieved."
        
        if action == "list":
            return "Directory listing complete."
        
        if action == "search":
            return "Search complete. Results found."
        
        if action == "execute":
            return "Command executed successfully."
        
        if action in ["start", "stop"]:
            return f"Service {action} operation complete."
        
        if action in ["check", "verify"]:
            status = result.get("result", "operational")
            return f"Status check complete. System is {status}."
        
        if action == "test":
            return "Test execution complete. Results available."
        
        # Question responses
        if action.startswith("what_"):
            return f"Here's what I found. {result.get('result', 'Information retrieved.')}."
        
        if action.startswith("where_"):
            return f"Location identified. {result.get('result', 'Resource found.')}."
        
        if action == "how_to":
            return f"Here's how to proceed. {result.get('result', 'Instructions available.')}."
        
        # Default
        return "Task complete. Operation successful."
    
    def _generate_error_text(
        self,
        intent: Intent,
        result: Dict[str, Any]
    ) -> str:
        """Generate error response text"""
        error = result.get("error", "Unknown error occurred")
        
        return f"I encountered an issue. {error}. Let me know how you'd like to proceed."
    
    def get_pending_requests(self) -> list:
        """Get list of pending requests"""
        return list(self.pending_requests.values())

# Made with Bob
