"""
Agent Lee OS – Local Chat UI
============================

This Python script provides a simple desktop chat window for interacting
with a local language model (e.g. Microsoft’s Phi‑3.5 Mini via the
Foundry Local runtime) and performing basic system health queries.

The goal of this script is to serve as a starting point for your
``Agent Lee OS`` assistant. It uses the built‑in ``tkinter`` GUI
library to create a window with a scrolling chat history and an input
field. When you enter a message and press ``Send``, the script calls
``query_model()`` to obtain a response from your local LLM and
displays the result in the chat window.

Key features:

* **Local model integration:** The ``query_model()`` function is a
  placeholder that you should modify to call your installed model via
  Microsoft Foundry Local, Ollama, or another offline runtime. See the
  comments inside ``query_model()`` for guidance.
* **System health integration:** The ``load_health_snapshot()``
  function reads a JSON snapshot created by your PowerShell monitor
  (for example, ``Leeway-SystemMonitor.ps1``) and displays a summary
  of CPU, memory, and disk usage. This allows the model to reason
  over real system data.
* **File system support:** Recognizes commands like ``list files in
  <directory>`` and sends a summary of the files (name, size, type)
  to the model for analysis.  You can ask the model to organize or
  summarize your files based on this context.
* **Extensibility:** You can add buttons or menu items to launch
  repair scripts, send health data directly to the model, or perform
  other actions as you evolve the Agent Lee assistant.

Requirements
------------

* Python 3.8 or later.
* The ``tkinter`` library (included with the standard Windows Python
  installer).  
* A local LLM runtime (e.g. Foundry Local) with the Phi‑3.5 Mini model
  downloaded.

Usage
-----

Run this script from a Windows terminal or create a shortcut.  It
assumes that a file named ``health_log.json`` exists in the same
directory (generated by your monitor script).  Replace the
implementation of ``query_model()`` to connect to your local model.

"""

import json
import os
import subprocess
import tkinter as tk
from tkinter import scrolledtext
from pathlib import Path
from typing import Dict, Any, Optional, List


def query_model(prompt: str) -> str:
    """Send a prompt to the local language model and return the reply.

    This function attempts to call a locally installed language model
    using the Microsoft Foundry Local CLI. It reads the model identifier
    from the `CEREBRAL_FOUNDRY_MODEL` environment variable if present;
    otherwise it defaults to ``phi-3-5-mini-instruct``.
    """
    model = os.environ.get("CEREBRAL_FOUNDRY_MODEL", "phi-3-5-mini-instruct")
    try:
        # Attempt to invoke the model via Foundry Local. ``--format plain``
        # returns plain text without metadata. Capture both stdout and stderr.
        result = subprocess.run([
            "foundry", "local", "run",
            "--model", model,
            "--format", "plain",
            prompt
        ], capture_output=True, text=True, check=True)
        return result.stdout.strip()
    except Exception:
        # Fallback: return a simple echo so the UI remains usable during
        # development even if the model or Foundry CLI are not available.
        return f"(mock) {prompt}"


def load_health_snapshot(path: Path) -> Optional[Dict[str, Any]]:
    """Load a health snapshot from ``health_log.json`` if it exists.

    The snapshot should be produced by your PowerShell monitor script
    (e.g. ``Leeway-SystemMonitor.ps1``) and contains fields such as
    ``CPU_Pct``, ``MEM_Pct``, ``Volumes``, and ``DiskSignals``.  If
    the file does not exist or cannot be parsed, returns ``None``.
    """
    if not path.exists():
        return None
    try:
        with path.open("r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


def get_file_info(directory: str, max_entries: int = 50) -> Optional[List[Dict[str, Any]]]:
    """Return information about files under ``directory``.

    This helper walks the given directory recursively and returns a
    summary list of file entries.  Each entry includes the file
    path (relative to the input directory), size in bytes, and file
    extension.  The number of returned entries is capped by
    ``max_entries`` to avoid overwhelming the model with too much
    context.  If the directory cannot be read, returns ``None``.
    """
    try:
        base_path = Path(directory).expanduser().resolve()
        entries: List[Dict[str, Any]] = []
        for root, dirs, files in os.walk(base_path):
            for fname in files:
                fpath = Path(root) / fname
                try:
                    entries.append({
                        "path": str(fpath.relative_to(base_path)),
                        "size": fpath.stat().st_size,
                        "ext": fpath.suffix.lower()
                    })
                    if len(entries) >= max_entries:
                        return entries
                except Exception:
                    continue
        return entries
    except Exception:
        return None


class AgentLeeUI(tk.Tk):
    """A simple chat window for Agent Lee OS."""

    def __init__(self, health_file: Path) -> None:
        super().__init__()
        self.title("Agent Lee OS Chat")
        self.geometry("600x500")
        self.health_file = health_file

        # Create chat display
        self.chat_display = scrolledtext.ScrolledText(self, wrap=tk.WORD, state=tk.DISABLED)
        self.chat_display.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)

        # Create input frame with entry and send button
        input_frame = tk.Frame(self)
        input_frame.pack(fill=tk.X, padx=10, pady=(0, 10))

        self.input_entry = tk.Entry(input_frame)
        self.input_entry.pack(side=tk.LEFT, fill=tk.X, expand=True)

        send_button = tk.Button(input_frame, text="Send", command=self.on_send)
        send_button.pack(side=tk.RIGHT, padx=(5, 0))

        # Create health summary label
        self.health_label = tk.Label(self, text="System health: unknown")
        self.health_label.pack(fill=tk.X, padx=10, pady=(0, 10))

        # Periodically update health information
        self.after(5000, self.refresh_health)

    def append_chat(self, sender: str, message: str) -> None:
        """Append a message to the chat display."""
        self.chat_display.configure(state=tk.NORMAL)
        self.chat_display.insert(tk.END, f"{sender}: {message}\n")
        self.chat_display.configure(state=tk.DISABLED)
        self.chat_display.see(tk.END)

    def on_send(self) -> None:
        """Handle the send button click and route the request."""
        user_input = self.input_entry.get().strip()
        if not user_input:
            return
        # Clear input field and show the user's message
        self.input_entry.delete(0, tk.END)
        self.append_chat("You", user_input)
        # Generate a response using our command handler
        try:
            response = self.handle_user_input(user_input)
        except Exception as ex:
            response = f"Error: {ex}"
        self.append_chat("Agent Lee", response)

    def handle_user_input(self, text: str) -> str:
        """Interpret and respond to user commands.

        This method inspects the user's input and assembles a prompt
        that provides the current system context (health snapshot
        and/or file information) before sending it to the model.  It
        understands a few simple commands:

        * ``list files in <dir>`` – returns a summary of files in
          the specified directory.
        * ``health`` or ``check system`` – returns the current health
          status from ``health_log.json``.
        For all other inputs, it sends the system health context plus
        the raw query to the model.
        """
        lower = text.lower()
        health = load_health_snapshot(self.health_file)
        # Prepare context prefix
        health_context = json.dumps(health or {}, ensure_ascii=False)
        # Persona description: this string instructs the model to adopt
        # Agent Lee's hip‑hop style, deep computing knowledge, and LEEWAY
        # compliance when formulating responses.  Feel free to adjust
        # the tone or content of the persona to suit your preferences.
        persona = (
            "You are Agent Lee: a hip‑hop‑flavored AI assistant with deep "
            "knowledge of music, street culture, and computer systems. You "
            "speak in a laid‑back, conversational tone, using the slang and "
            "metaphors of hip‑hop when appropriate.  You respect privacy, "
            "adhere to Microsoft's security policies, and you understand the "
            "LEEWAY coding standards for system scripts.  When discussing "
            "the user's system or files, you explain technical details as if "
            "you're storytelling over a beat, making complex topics easy to "
            "understand."
        )
        # Command: list files in <dir>
        if lower.startswith("list files"):
            # Parse the directory after "list files" or "list files in"
            # Accept forms like "list files C:\Users\Agent Lee\Documents" or
            # "list files in ~/Downloads".
            parts = text.split(None, 2)
            target_dir = None
            if len(parts) >= 3:
                # The third part may include "in" or be the directory itself
                maybe = parts[2].strip()
                if maybe.lower().startswith("in "):
                    target_dir = maybe[3:].strip()
                else:
                    target_dir = maybe
            if not target_dir:
                return "Please specify a directory path after 'list files'."
            files = get_file_info(target_dir)
            if files is None:
                return f"Unable to read directory: {target_dir}"
            context = json.dumps({"health": health or {}, "files": files}, ensure_ascii=False)
            prompt = (
                f"{persona}\n\nGiven the following system context and file list, "
                "answer the user's request in your own voice."
                f"\n\nContext: {context}\n\nUser request: {text}"
            )
            return query_model(prompt)
        # Command: check health or health status
        elif any(kw in lower for kw in ["health", "check system", "system status"]):
            prompt = (
                f"{persona}\n\nYou are acting as the user's personal system "
                "doctor. Summarize the current system health and explain "
                "any critical issues using the provided health snapshot data."
                f"\n\nHealth snapshot: {health_context}"
            )
            return query_model(prompt)
        # Default: general query with system context
        else:
            prompt = (
                f"{persona}\n\nUse the system context to answer the "
                "user's question in your unique style."
                f"\n\nSystem context: {health_context}\n\nUser request: {text}"
            )
            return query_model(prompt)

    def refresh_health(self) -> None:
        """Load and display system health summary."""
        snapshot = load_health_snapshot(self.health_file)
        if snapshot:
            cpu = snapshot.get("CPU_Pct", "?")
            mem = snapshot.get("MEM_Pct", "?")
            volumes = snapshot.get("Volumes", [])
            vol_status = ", ".join(f"{v['Drive']} {v['FreeGB']}GB free" for v in volumes)
            summary = f"CPU: {cpu}%  |  MEM: {mem}%  |  {vol_status}"
        else:
            summary = "System health: no data"
        self.health_label.configure(text=summary)
        # Schedule next refresh in 60 seconds
        self.after(60000, self.refresh_health)


def main() -> None:
    health_path = Path(__file__).with_name("health_log.json")
    app = AgentLeeUI(health_file=health_path)
    app.mainloop()


if __name__ == "__main__":
    main()