export default function Page() {
  const cards = [
    ["State", "LOCKED / CONTRACT ONLY / NO EXECUTE"],
    ["Approval Granted", "false"],
    ["Authority Unlocked", "false"],
    ["Execution Authorized", "false"],
    ["Device Control Authorized", "false"],
    ["Physical Action Authorized", "false"]
  ];

  const blocked = [
    "ADB pair/connect/shell/install",
    "scrcpy control",
    "Samsung DeX launch",
    "Smart View cast",
    "SmartThings physical action",
    "Apple pairing or Apple TV remote",
    "Quick Share transfer",
    "Bluetooth pairing",
    "Screen recording",
    "Camera or microphone activation",
    "Router mutation",
    "Network or port scan",
    "Phone, TV, lock, appliance, or vehicle control"
  ];

  return (
    <main style={{ minHeight: "100vh", padding: "48px", background: "#05070d", color: "#f8fafc", fontFamily: "Arial, sans-serif" }}>
      <section style={{ maxWidth: "1100px", margin: "0 auto" }}>
        <p style={{ color: "#38bdf8", fontSize: "14px", letterSpacing: "0.14em", textTransform: "uppercase", marginBottom: "12px" }}>
          LeeWay Device Continuity Locked Stub
        </p>
        <h1 style={{ fontSize: "42px", lineHeight: "1.1", margin: "0 0 16px" }}>
          Wireless Debugging Locked Stub
        </h1>
        <p style={{ fontSize: "18px", lineHeight: "1.7", color: "#cbd5e1", maxWidth: "920px" }}>
          Locked ADB and wireless debugging boundary page.
        </p>

        <div style={{ marginTop: "28px", padding: "20px", border: "1px solid #7f1d1d", borderRadius: "18px", background: "rgba(127,29,29,0.28)" }}>
          <strong style={{ color: "#fecaca" }}>LOCKED BOUNDARY:</strong>
          <span style={{ color: "#fee2e2" }}> This page is informational only. It does not execute, pair, cast, scan, record, unlock, connect, or control any device.</span>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(230px,1fr))", gap: "14px", marginTop: "28px" }}>
          {cards.map(([label, value]) => (
            <div key={label} style={{ border: "1px solid #1e293b", background: "#0f172a", borderRadius: "16px", padding: "18px" }}>
              <div style={{ color: "#94a3b8", fontSize: "13px" }}>{label}</div>
              <div style={{ color: "#f8fafc", fontSize: "18px", fontWeight: 700, marginTop: "6px" }}>{value}</div>
            </div>
          ))}
        </div>

        <h2 style={{ marginTop: "36px", fontSize: "24px" }}>Blocked actions</h2>
        <ul style={{ color: "#cbd5e1", lineHeight: "1.9", columns: 2 }}>
          {blocked.map((item) => <li key={item}>{item}</li>)}
        </ul>

        <div style={{ marginTop: "32px", padding: "18px", border: "1px solid #164e63", borderRadius: "16px", background: "rgba(8,47,73,0.4)", color: "#bae6fd" }}>
          Next authority lane requires a future owner-approved single-use contract, proof before action, proof after action, and immediate lockback.
        </div>

        <p style={{ color: "#64748b", marginTop: "32px", fontSize: "13px" }}>
          Route: /wireless-debugging-locked-stub | Generated by 391-device-continuity-create-locked-ui-api-stubs.ps1
        </p>
      </section>
    </main>
  );
}
