# ============================================================
# AgentLeeCreationKernelHelpers.ps1
# Real image/video creation helper for Agent Lee.
# Path-independent version.
#
# Usage:
# . "$env:LEEWAY_ROOT\scripts\AgentLeeCreationKernelHelpers.ps1"
# $result = New-AgentLeeImageReal -Prompt "blue lion on a chess board"
# ============================================================

$CandidateRoot = Split-Path -Parent $PSScriptRoot
$Loader = Join-Path $CandidateRoot ".leeway-runtime\Import-LeewayRuntime.ps1"

if (Test-Path $Loader) {
    . $Loader
    $script:AgentLeeRoot = $env:LEEWAY_ROOT
} elseif ($env:LEEWAY_ROOT -and (Test-Path $env:LEEWAY_ROOT)) {
    $script:AgentLeeRoot = $env:LEEWAY_ROOT
} else {
    $script:AgentLeeRoot = $CandidateRoot
}

function Get-AgentLeeCreationKernelConfig {
    $paths = @(
        (Join-Path $script:AgentLeeRoot "agent-lee-coding-mode\desktop-runtime\creation-kernel.json"),
        (Join-Path $script:AgentLeeRoot "agent-lee-coding-mode\runtime-fabric\creation-kernel.json"),
        (Join-Path $script:AgentLeeRoot "scripts\agent-lee-creation-kernel.json")
    )

    foreach ($p in $paths) {
        if (Test-Path $p) {
            try {
                $cfg = Get-Content $p -Raw | ConvertFrom-Json
                if ($cfg.status -eq "READY") {
                    return $cfg
                }
            } catch {}
        }
    }

    return $null
}

function New-AgentLeeImageReal {
    param(
        [Parameter(Mandatory=$true)]
        [string]$Prompt,

        [string]$HostOutputPath = "",

        [int]$Width = 512,
        [int]$Height = 512,
        [int]$Steps = 1,
        [int]$Seed = 77
    )

    $cfg = Get-AgentLeeCreationKernelConfig

    if ($null -eq $cfg) {
        throw "Agent Lee Creation Kernel config is not READY."
    }

    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"

    if ([string]::IsNullOrWhiteSpace($HostOutputPath)) {
        $outDir = Join-Path $script:AgentLeeRoot "Archive\generated-images"
        New-Item -ItemType Directory -Force -Path $outDir | Out-Null
        $HostOutputPath = Join-Path $outDir ("agent-lee-real-image-$stamp.png")
    }

    $containerOutputPath = "/outputs/agent-lee-real-image-$stamp.png"

    $body = [ordered]@{
        prompt = $Prompt
        outputPath = $containerOutputPath
        width = $Width
        height = $Height
        steps = $Steps
        guidance_scale = 0.0
        seed = $Seed
        return_base64 = $false
    }

    $res = Invoke-RestMethod -Uri $cfg.imageGenerateUrl -Method POST -ContentType "application/json" -Body ($body | ConvertTo-Json -Depth 30) -TimeoutSec 900

    if ($res.status -ne "READY") {
        throw ("Creation Kernel did not return READY: " + ($res | ConvertTo-Json -Depth 20))
    }

    docker cp ("{0}:{1}" -f $cfg.containerName, $containerOutputPath) $HostOutputPath | Out-Null

    if (-not (Test-Path $HostOutputPath)) {
        throw "docker cp did not produce host output image."
    }

    $bytes = (Get-Item $HostOutputPath).Length

    if ($bytes -lt 1000) {
        throw "Generated image is too small to trust."
    }

    return [ordered]@{
        status = "READY"
        prompt = $Prompt
        hostOutputPath = $HostOutputPath
        containerOutputPath = $containerOutputPath
        bytes = $bytes
        response = $res
        truth = "Real image generated by Agent Lee Creation Kernel."
    }
}

function New-AgentLeeProductVideoFromImage {
    param(
        [Parameter(Mandatory=$true)]
        [string]$ImagePath,

        [string]$VideoPath = ""
    )

    if (-not (Test-Path $ImagePath)) {
        throw "Input image does not exist: $ImagePath"
    }

    if ($null -eq (Get-Command ffmpeg -ErrorAction SilentlyContinue)) {
        throw "ffmpeg not found."
    }

    if ([string]::IsNullOrWhiteSpace($VideoPath)) {
        $outDir = Join-Path $script:AgentLeeRoot "Archive\generated-videos"
        New-Item -ItemType Directory -Force -Path $outDir | Out-Null
        $VideoPath = Join-Path $outDir ("agent-lee-product-video-" + (Get-Date -Format "yyyyMMdd-HHmmss") + ".mp4")
    }

    ffmpeg -y -loop 1 -i $ImagePath -t 4 -vf "scale=1280:720,format=yuv420p" -r 30 $VideoPath | Out-Null

    if (-not (Test-Path $VideoPath)) {
        throw "ffmpeg did not produce video output."
    }

    return [ordered]@{
        status = "READY"
        imagePath = $ImagePath
        videoPath = $VideoPath
        bytes = (Get-Item $VideoPath).Length
        truth = "Product video generated from image."
    }
}
